### ISSUE TITLE
Nginx tests failing on travis ci ubuntu

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Entropy#213]
I see failures with the errors:

```
Failed   EntropyTests.Diagnostics.DiagnosticsStatusCodesMvcTestsForNonExistingPage.NgnixX64NonWindows
Error Message:
 System.Exception : Failed to start Nginx
Stack Trace:
   at Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer.SetupNginx(String redirectUri, Uri originalUri)
   at Microsoft.AspNetCore.Server.IntegrationTesting.NginxDeployer.Deploy()
   at EntropyTests.TestServices.<RunSiteTest>d__4.MoveNext() in /home/travis/build/aspnet/Entropy/test/FunctionalTests/TestServices.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)Standard Output Messages:
 | Information [Diagnostics.StatusCodes.Mvc:Nginx:CoreClr:x64]: Executing command dotnet publish  --output "/tmp/67f9f5e2-3f92-4af4-9974-e7133ca74e35" --framework netcoreapp1.1 --configuration Debug 
 | Information [Diagnostics.StatusCodes.Mvc:Nginx:CoreClr:x64]: Removing environment variable ASPNETCORE_ENVIRONMENT
 | Information [Diagnostics.StatusCodes.Mvc:Kestrel:CoreClr:x64]: Host process shutting down.
 | Information [Diagnostics.StatusCodes.Mvc:Nginx:CoreClr:x64]: Microsoft (R) Build Engine version 15.2.47.30403
 | Information [Diagnostics.StatusCodes.Mvc:Nginx:CoreClr:x64]: Copyright (C) Microsoft Corporation. All rights reserved.
 | Information [Diagnostics.StatusCodes.Mvc:Nginx:CoreClr:x64]: 
 | Information [Diagnostics.StatusCodes.Mvc:Nginx:CoreClr:x64]:   Diagnostics.StatusCodes.Mvc -> /home/travis/build/aspnet/Entropy/samples/Diagnostics.StatusCodes.Mvc/bin/Debug/netcoreapp1.1/Diagnostics.StatusCodes.Mvc.dll
 | Warning [Diagnostics.StatusCodes.Mvc:Nginx:CoreClr:x64]: 
 | Information [Diagnostics.StatusCodes.Mvc:Nginx:CoreClr:x64]: 
 | Information [Diagnostics.StatusCodes.Mvc:Nginx:CoreClr:x64]: dotnet publish finished with exit code : 0
 | Information [Diagnostics.StatusCodes.Mvc:Nginx:CoreClr:x64]: Executing dotnet /tmp/67f9f5e2-3f92-4af4-9974-e7133ca74e35/Diagnostics.StatusCodes.Mvc.dll --server.urls http://localhost:36483/  --server Microsoft.AspNetCore.Server.Kestrel
 | Information [Diagnostics.StatusCodes.Mvc:Nginx:CoreClr:x64]: Removing environment variable ASPNETCORE_ENVIRONMENT
 | Information [Diagnostics.StatusCodes.Mvc:Nginx:CoreClr:x64]: SET ASPNETCORE_DETAILEDERRORS=true
 | Information [Diagnostics.StatusCodes.Mvc:Nginx:CoreClr:x64]: Started dotnet. Process Id : 16023
 | Warning [Diagnostics.StatusCodes.Mvc:Nginx:CoreClr:x64]: nginx: nginx: [emerg] invalid number of arguments in "user" directive in /tmp/tmpILYc5H.tmp:2
 | Information [Diagnostics.StatusCodes.Mvc:Nginx:CoreClr:x64]: Attempting to cancel process 16023
 | Information [Diagnostics.StatusCodes.Mvc:Nginx:CoreClr:x64]: 
 | Error [Diagnostics.StatusCodes.Mvc:Nginx:CoreClr:x64]: 
 | Warning [Diagnostics.StatusCodes.Mvc:Nginx:CoreClr:x64]: Unable to terminate the host process with process Id '16023
 | Information [Diagnostics.StatusCodes.Mvc:Nginx:CoreClr:x64]: Host process shutting down.
 | Information [Diagnostics.StatusCodes.Mvc:Nginx:CoreClr:x64]: [Time]: Total time taken for this test variation '0' seconds
```
https://travis-ci.org/aspnet/Entropy/jobs/215642938#L3988-L4024

**Comment by BrennanConroy** [comment]
Fixed with https://github.com/aspnet/Entropy/issues/214
