### ISSUE TITLE
Release branch doesn't compile

### ISSUE THREAD

**Issue by simonech** [aspnet/Entropy#27]
Just getting the repo from git, with no change done, the solution doesn't build.

The project Mvc.CustomRoutingConvention gives the following 10 errors: (all project references are downloaded)

```
25>C:\Users\user\Documents\GitHub\Entropy\samples\Mvc.CustomRoutingConvention\NameSpaceRoutingConvention.cs(1,28): ASP.NET 5.0 error CS0234: The type or namespace name 'ApplicationModels' does not exist in the namespace 'Microsoft.AspNet.Mvc' (are you missing an assembly reference?)
25>C:\Users\user\Documents\GitHub\Entropy\samples\Mvc.CustomRoutingConvention\NameSpaceRoutingConvention.cs(5,49): ASP.NET 5.0 error CS0246: The type or namespace name 'IApplicationModelConvention' could not be found (are you missing a using directive or an assembly reference?)
25>C:\Users\user\Documents\GitHub\Entropy\samples\Mvc.CustomRoutingConvention\NameSpaceRoutingConvention.cs(7,27): ASP.NET 5.0 error CS0246: The type or namespace name 'ApplicationModel' could not be found (are you missing a using directive or an assembly reference?)
25>C:\Users\user\Documents\GitHub\Entropy\samples\Mvc.CustomRoutingConvention\Startup.cs(18,61): ASP.NET 5.0 error CS1503: Argument 1: cannot convert from 'NamespaceRouting.NameSpaceRoutingConvention' to 'Microsoft.AspNet.Mvc.ApplicationModel.IGlobalModelConvention'
25>C:\Users\user\Documents\GitHub\Entropy\samples\Mvc.CustomRoutingConvention\NameSpaceRoutingConvention.cs(14,51): ASP.NET 5.0 error CS0246: The type or namespace name 'AttributeRouteModel' could not be found (are you missing a using directive or an assembly reference?)
25>C:\Users\user\Documents\GitHub\Entropy\samples\Mvc.CustomRoutingConvention\NameSpaceRoutingConvention.cs(1,28): ASP.NET Core 5.0 error CS0234: The type or namespace name 'ApplicationModels' does not exist in the namespace 'Microsoft.AspNet.Mvc' (are you missing an assembly reference?)
25>C:\Users\user\Documents\GitHub\Entropy\samples\Mvc.CustomRoutingConvention\NameSpaceRoutingConvention.cs(5,49): ASP.NET Core 5.0 error CS0246: The type or namespace name 'IApplicationModelConvention' could not be found (are you missing a using directive or an assembly reference?)
25>C:\Users\user\Documents\GitHub\Entropy\samples\Mvc.CustomRoutingConvention\NameSpaceRoutingConvention.cs(7,27): ASP.NET Core 5.0 error CS0246: The type or namespace name 'ApplicationModel' could not be found (are you missing a using directive or an assembly reference?)
25>C:\Users\user\Documents\GitHub\Entropy\samples\Mvc.CustomRoutingConvention\Startup.cs(18,61): ASP.NET Core 5.0 error CS1503: Argument 1: cannot convert from 'NamespaceRouting.NameSpaceRoutingConvention' to 'Microsoft.AspNet.Mvc.ApplicationModel.IGlobalModelConvention'
25>C:\Users\user\Documents\GitHub\Entropy\samples\Mvc.CustomRoutingConvention\NameSpaceRoutingConvention.cs(14,51): ASP.NET Core 5.0 error CS0246: The type or namespace name 'AttributeRouteModel' could not be found (are you missing a using directive or an assembly reference?)
```
I just checked, and the dll that gets downloaded from myget (Microsoft.AspNet.Mvc.Core\6.0.0-beta1-11874) doesn't contain any definition of the `ApplicationModels` namespace.

Also references in one of the projects fail to load:]
![image](https://cloud.githubusercontent.com/assets/61557/4959356/9ae5d3fc-66b7-11e4-933e-46127c93f75d.png)

and the error list says:
```
Microsoft.Framework.Runtime.Roslyn.RoslynCompilationException: error CS0656: Missing compiler required member 'System.Collections.Generic.EqualityComparer`1.Equals'
error CS0656: Missing compiler required member 'System.Collections.Generic.EqualityComparer`1.GetHashCode'
error CS0656: Missing compiler required member 'System.Collections.Generic.EqualityComparer`1.get_Default'
   at Microsoft.Framework.Runtime.Roslyn.RoslynProjectReference.Load(IAssemblyLoadContext loadContext)
   at Microsoft.Framework.DesignTimeHost.ApplicationContext.Initialize(String appPath, String configuration, Boolean triggerBuildOutputs)
   at Microsoft.Framework.DesignTimeHost.ApplicationContext.Calculate()
   at Microsoft.Framework.DesignTimeHost.ApplicationContext.DoProcessLoop()
   at Microsoft.Framework.DesignTimeHost.ApplicationContext.ProcessLoop(Object state)	
```
The same project also gives the following errors... those kind of make sense as the projectreference project doesn't have config for the CoreCLR

```
Show Details	Severity	Code	Description	Project	File	Line
	Error	CS0234	The type or namespace name 'ApplicationModels' does not exist in the namespace 'Microsoft.AspNet.Mvc' (are you missing an assembly reference?)	Mvc.CustomRoutingConvention.ASP.NET 5.0	NameSpaceRoutingConvention.cs	1
	Error	CS0234	The type or namespace name 'ProjectReference' does not exist in the namespace 'Project' (are you missing an assembly reference?)	Project.Dependencies.ASP.NET Core 5.0	Program.cs	7
	Error	CS0234	The type or namespace name 'ProjectReference' does not exist in the namespace 'Project' (are you missing an assembly reference?)	Project.Dependencies.ASP.NET Core 5.0	Program.cs	7
	Error	CS0234	The type or namespace name 'ProjectReference' does not exist in the namespace 'Project' (are you missing an assembly reference?)	Project.Dependencies.ASP.NET Core 5.0	Program.cs	7
	Error	CS0518	Predefined type 'System.String' is not defined or imported	Project.Dependencies.ASP.NET Core 5.0	Program.cs	17
	Error	CS1061	'string' does not contain a definition for 'ToLower2' and no extension method 'ToLower2' accepting a first argument of type 'string' could be found (are you missing a using directive or an assembly reference?)	Project.Dependencies.ASP.NET Core 5.0	Program.cs	17
```

**Comment by JunTaoLuo** [comment]
This looks like a very old issue that is no longer relevant. I have been verifying our release branch recently and there are no major problems.
